version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app/src/frontend
    command: >
      sh -c "npm install &&
             npm run build &&
             npm run start"
