FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"

RUN dfx generate

EXPOSE 8000

CMD ["sh", "-c", "dfx start --clean --background && dfx deploy && npm start"]
